# Generated by Django 3.0 on 2019-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='keywords',
            field=models.TextField(default=None),
        ),
    ]
